# PostgreSQL 接続
spring.datasource.url=jdbc:postgresql://localhost:5432/javase11_study
spring.datasource.username=javastudy
spring.datasource.password=javastudy
spring.datasource.driver-class-name=org.postgresql.Driver
