# ユーザー名：8〜20、英数のみ
regex.username=^(?=.{8,20}$)[A-Za-z0-9]+$

# パスワード：8〜72、英字/数字/記号(!/&/@)を各1つ以上、かつそれ“だけ”
regex.password=^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[!/&@])[A-Za-z0-9!/&@]{8,72}$

# 解答選択肢：A〜E と U（Unknown）だけ、最大20文字まで（複数選択の連結想定）
regex.selectedoption=^(?:[A-E]|U){1,20}$

# 参考書カラー名：英数・日本語・空白・ハイフン、1〜30
regex.bookcolor.name=^[A-Za-zぁ-んァ-ヶ一-龯0-9\\s-]{1,30}$

# 権限名：ROLE_ + 英大/数字/アンダースコア（全体20字以内に収まる想定）
regex.authority.name=^ROLE_[A-Z0-9_]{1,15}$

# 権限名：英大/数字/アンダースコア（全体20字以内に収まる想定）
regex.authority.systemname=^[A-Z0-9_]{1,15}$

# 問題番号：1〜3桁の数字
regex.questions.no=^[0-9]{1,3}$
