# ViewId 署名用のシークレット（init と同じ固定値を継続利用）
spring.application.name=spring_javase11_study
spring.config.import=classpath:config/db.properties,classpath:config/regex.properties
spring.profiles.group.dev[0]=init

spring.messages.basename=config/error,config/regex,config/labels,my_login/config/error,my_util/config/error
spring.messages.encoding=UTF-8
spring.messages.cache-duration=1h
spring.messages.fallback-to-system-locale=false

# ふだんは初期化をしない
spring.sql.init.mode=never

# JPA は自動DDLをしない
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 本体ログの出力先（logback が参照）
logging.file.name=logs/javastudy.log
